version: "3"

services:
  app:
    container_name: miner-stock-checker
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - backend

networks:
  backend:
